Doodle with vgo Proxy
sonatype-nexus-community/nexus-repository-vgo pull request #1
Opened 2018-05-15 15:57 UTC by DarthHater

This PR makes some of the initial changes to get a Proxy implementation working. This work follows a bit of what Russ Cox laid out in: https://research.swtch.com/vgo-module

This pull request makes the following changes:
* A slew, lots of necessary files
* Adds in Docker for building
* Start of docs related to use

2018-05-15 16:00 UTC, DarthHater commented
This likely needs #2 implemented before it becomes super useful, but it is the work needed to get a proxy to spin up in the Nexus Repo UI, and work sort of bare bones.

2019-02-03 20:21 UTC, incu6us requested changes
got some warnings while the plugin starting:
```
WARN  [FelixStartLevel] *SYSTEM com.google.inject.spi.InjectionPoint - Method: public void org.sonatype.repository.vgo.internal.VgoRecipeSupport.setBrowseUnsupportedHandler(org.sonatype.nexus.repository.view.handlers.BrowseUnsupportedHandler) is not annotated with @Inject but is overriding a method that is annotated with @javax.inject.Inject.  Because it is not annotated with @Inject, the method will not be injected. To fix this, annotate the method with @Inject.
```

2019-02-03 20:21 UTC, incu6us commented on Dockerfile
> +ARG NEXUS_VERSION=3.14.0
duplicated item

2019-02-03 20:21 UTC, incu6us commented on src/main/java/org/sonatype/repository/vgo/internal/VgoContentValidator.java
> +      if (contentName.endsWith(".mod")) {
probably if simplify into one line it could be more readable? ex.:
```suggestion
     if (contentName != null && contentName.endsWith(".mod")) {
```

2019-02-03 20:21 UTC, incu6us commented on Dockerfile
> +COPY --from=build /nexus-repository-vgo/target/nexus-repository-vgo-${VGO_VERSION}.jar ${TARGET_DIR}
the next line should be added to start the plugin:
```
RUN echo "reference\:file\:org/sonatype/nexus/plugins/nexus-repository-vgo/${VGO_VERSION}/nexus-repository-vgo-${VGO_VERSION}.jar = 200" >> /opt/sonatype/nexus/etc/karaf/startup.properties
```

2019-03-17 08:29 UTC, merged